server:
  port: 8081
spring:
  application:
    name: "registrar-usuarios"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://localhost:3306/crediyadb?useSSL=false&serverTimezone=UTC"
    username: "user"
    password: "password"
    driverClassName: "com.mysql.cj.jdbc.Driver"
routes:
  paths:
    usuarios: "/api/v1/usuarios"
    usuariosById: "/api/v1/usuarios/{id:\\d+}"
    usuariosByEmail: "/api/v1/usuarios/{email:[\\w-\\.]+@[\\w-\\.]+\\.[a-z]{2,}}"
    login: "/api/v1/login"
adapters:
  r2dbc:
    host: "${MYSQL_HOST:localhost}"
    port: "${MYSQL_PORT:3306}"
    database: "${MYSQL_DB:crediyadb}"
    username: "${MYSQL_USER:crediya}"
    password: "${MYSQL_PASSWORD:password}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

jwt:
  keys:
    private-key: classpath:keys/private_key.pem
    public-key: classpath:keys/public_key.pem
  expiration: 3600000


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  packages-to-scan: "co.com.crediya.api"
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
